create table if not exists public.creators (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  url text not null,
  description text not null,
  "imageURL" text
);

alter table public.creators enable row level security;

drop policy if exists "Public can read creators" on public.creators;
create policy "Public can read creators"
  on public.creators
  for select
  to anon
  using (true);

drop policy if exists "Public can insert creators" on public.creators;
create policy "Public can insert creators"
  on public.creators
  for insert
  to anon
  with check (true);

drop policy if exists "Public can update creators" on public.creators;
create policy "Public can update creators"
  on public.creators
  for update
  to anon
  using (true)
  with check (true);

drop policy if exists "Public can delete creators" on public.creators;
create policy "Public can delete creators"
  on public.creators
  for delete
  to anon
  using (true);
